
export enum Genre {
  FANTASY = 'Fantasy',
  SCIFI = 'Sci-Fi',
  MYSTERY = 'Mystery',
  HORROR = 'Horror',
  THRILLER = 'Thriller',
  DOCUMENTARY = 'Documentary'
}

export enum ViewMode {
  HOME = 'home',
  ADVENTURE = 'adventure',
  SETUP = 'setup',
  FEEDBACK = 'feedback'
}

export type GeminiVoice = 'Puck' | 'Charon' | 'Kore' | 'Fenrir' | 'Zephyr';

export enum NarratorMode {
  SINGLE = 'Single Narrator',
  MULTI = 'Multiple Characters'
}

export interface AdventureConfig {
  genre: Genre;
  topic: string;
  language: string;
  voice: GeminiVoice;
  mode: NarratorMode;
  durationMinutes?: number;
  movieName?: string; // Specialized field for CINE mode
}

export interface StoryState {
  genre: Genre | null;
  isActive: boolean;
  voice: GeminiVoice;
  transcriptionHistory: Array<{
    role: 'user' | 'model';
    text: string;
  }>;
}

/**
 * Interface for cinematic sound orchestrator production scripts.
 */
export interface OrchestratorScript {
  title: string;
  scenes: Array<{
    text: string;
    speaker_type: 'Narrator' | 'Male_Character' | 'Female_Character';
    emotion: string;
    bgm_mood: string;
  }>;
}

/**
 * Interface for infinite storytelling parts generated by StoryGuru.
 */
export interface GuruScript {
  title: string;
  segments: Array<{
    speaker: string;
    text: string;
    voice_id: GeminiVoice;
    speed: 'slow' | 'normal' | 'fast';
    emotion: string;
  }>;
  summary: string;
}

/**
 * Wrapper for a story segment in the StoryGuru experience.
 */
export interface StoryPart {
  id: number;
  title: string;
  script: GuruScript;
  buffers: Record<number, AudioBuffer>;
}

/**
 * Casting information for VoiceGuru characters.
 */
export interface CastMember {
  id: string;
  name: string;
  role: string;
  age_group: 'Child' | 'Teen' | 'Adult' | 'Senior';
  is_supernatural: boolean;
  assigned_voice: GeminiVoice;
}

/**
 * Manifest containing the full production plan for VoiceGuru.
 */
export interface VoiceGuruManifest {
  title: string;
  directors_notes: string;
  scenes: Array<{
    cast_id: string;
    text: string;
    emotion: string;
    pacing: 'slow' | 'normal' | 'fast';
  }>;
  cast: CastMember[];
}
